In [1]:
import numpy as np
print(np.__version__)

2.3.3


In [3]:
python_list=[1,2,3,4]
print(python_list)

[1, 2, 3, 4]


In [4]:
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [5]:
arr=np.zeros(3)
print(arr)

[0. 0. 0.]


In [6]:
arr=np.ones(3)
print(arr)

[1. 1. 1.]


In [7]:
arr=np.full((2,2),7)
print(arr)

[[7 7]
 [7 7]]


In [9]:
arr=np.arange(1,10,2) #start stop step
print(arr)

[1 3 5 7 9]


In [10]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
arr=np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)

(2, 3)


In [16]:
arr=np.array([[1,2,3],
              [4,5,6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [18]:
arr=np.array([1.2,2.5,3.6])
print(arr.dtype)
arr_int=arr.astype(int)
print(arr_int)
print(arr_int.dtype)

float64
[1 2 3]
int64


In [31]:
arr=np.array([1,2,3,4])
print(arr.sum())
print(arr.max())
print(arr.min())
print(arr.std())
print(arr.mean())
print(arr.var())

10
4
1
1.118033988749895
2.5
1.25


In [34]:
arr=np.array([10,20,30,40,50])
print(arr[[0,2]])#fancy indexing
print(arr[arr>25])#boolian masking

[10 30]
[30 40 50]


In [36]:
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(2,3)) #2 row 3 col if dimension match

[[1 2 3]
 [4 5 6]]


In [38]:
#nd to 1d array convert
arr=np.array([[1,2,3],
             [4,5,6]])
print(arr.ravel()) #//view only 
print(arr.flatten()) #// copy

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [3]:
arr=np.array([10,20,30,40])
new_arr=np.insert(arr,2,100)#2 is position 100 inserted value
print(new_arr)

[ 10  20 100  30  40]


In [20]:
arr=np.array([[1,2,3],
             [4,5,6]])
new_arr1=np.insert(arr,1,[100],axis=0) 
new_arr2=np.insert(arr,1,[100],axis=1) 
print(new_arr1)
print("-------------------")
print()
print(new_arr2)

[[  1   2   3]
 [100 100 100]
 [  4   5   6]]
-------------------

[[  1 100   2   3]
 [  4 100   5   6]]


In [8]:
arr=np.array([10,20,30,40])
new_arr=np.append(arr,[50,60,70])
print(new_arr)

[10 20 30 40 50 60 70]


In [18]:
arr1=np.array([1,2,3])
arr2=np.array([1,2,3])
new_arr1=np.concatenate((arr1, arr2), axis=0)
print(new_arr1)

[1 2 3 1 2 3]


In [22]:
arr=np.array([10,20,30,40]) 
print(arr)
new_arr=np.delete(arr,0)
print(new_arr)

[10 20 30 40]
[20 30 40]


In [24]:
arr=np.array([[1,2,3],
             [4,5,6]])
print(arr)
print()
new_arr=np.delete(arr,0,axis=0)
print(new_arr)


[[1 2 3]
 [4 5 6]]

[[4 5 6]]


In [25]:
arr=np.array([[1,2,3],
             [4,5,6]])
print(arr)
print()
new_arr=np.delete(arr,0,axis=1)
print(new_arr)

[[1 2 3]
 [4 5 6]]

[[2 3]
 [5 6]]


In [26]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
new_arr1=np.vstack((arr1,arr2))
new_arr2=np.hstack((arr1,arr2))
print(new_arr1)
print()
print(new_arr2)

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [28]:
arr=np.array([10,20,30 ,40,50,60])
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [29]:
#brodcasting
prices=np.array([100,200,300])
discount=10
final_prices=prices-(prices*discount/100)
print(final_prices)

[ 90. 180. 270.]


In [33]:
#handling missing values
#np.isnan()-> detect missing value
#np.nan_to_num()
#np.isinf()

arr=np.array([1,2,3,4])
print(np.isnan(arr))

arr=np.array([1,np.nan,3,4])
print(np.isnan(arr))

print(np.nan==np.nan)#we can not compare it directly

[False False False False]
[False  True False False]
False


In [34]:
#handle missing values
arr=np.array([1,np.nan,3,4])
new_arr=np.nan_to_num(arr,nan=100)
print(new_arr)

[  1. 100.   3.   4.]


In [37]:
arr=np.array([1,np.inf,3,4,-np.inf,6])
print(np.isinf(arr))
new_arr=np.nan_to_num(arr,posinf=100,neginf=-100)
print(new_arr)

[False  True False False  True False]
[   1.  100.    3.    4. -100.    6.]
